import type { SettingsScope, SnapshotStore } from '@deepseek-ai/dsh-client-runtime/client'
import { createSnapshotStore } from '@deepseek-ai/dsh-client-runtime/client'
export interface FieldSpec { field: string; format: (v: unknown) => string; parse: (t: string) => FieldWrite | undefined }
export type FieldWrite = { kind: 'set'; value: unknown } | { kind: 'clear' }
export interface FieldState { text: string; overridden: boolean; invalid: boolean }
export interface CardShell { available: boolean; exposed: boolean; writable: boolean; dirty: boolean; invalid: boolean; saving: boolean; failed: boolean }
export interface CardActions { edit: (f: string, t: string) => void; resetField: (f: string) => void; save: () => void; discard: () => void }
export function booleanField(field: string): FieldSpec { return { field, format: v => typeof v === 'boolean' ? String(v) : '', parse: t => t === 'true' ? { kind: 'set', value: true } : t === 'false' ? { kind: 'set', value: false } : undefined } }
export function stringField(field: string, valid?: (v: string) => boolean): FieldSpec { return { field, format: v => typeof v === 'string' ? v : '', parse: t => { const s = t.trim(); if (s === '') return { kind: 'clear' }; if (valid && !valid(s)) return undefined; return { kind: 'set', value: s } } } }
export function numberField(field: string): FieldSpec { return { field, format: v => typeof v === 'number' ? String(v) : '', parse: t => { const s = t.trim(); if (s === '') return { kind: 'clear' }; const n = Number(s); return Number.isFinite(n) ? { kind: 'set', value: n } : undefined } } }
interface StagedEdit { text: string; clear: boolean }
interface PlannedWrite { field: string; run: (() => Promise<boolean>) | undefined }
export class CardForm<T> {
  private readonly specs: Map<string, FieldSpec>; private readonly staged = new Map<string, StagedEdit>(); private readonly listeners = new Set<() => void>(); private saving = false; private failed = false
  constructor(private readonly scope: SettingsScope<T>, specs: FieldSpec[]) { this.specs = new Map(specs.map(s => [s.field, s])); scope.subscribe(() => this.publish()) }
  bind<S>(project: () => S): SnapshotStore<S> { const store = createSnapshotStore(project()); this.listeners.add(() => store.set(project())); return store }
  shell(): CardShell { const snap = this.scope.getSnapshot(); const plan = this.plan(); return { available: snap.status !== 'loading', exposed: snap.status === 'ready', writable: snap.writable, dirty: plan.length > 0, invalid: plan.some(p => p.run === undefined), saving: this.saving, failed: this.failed } }
  field(field: string): FieldState { const spec = this.specs.get(field)!; const staged = this.staged.get(field); if (!staged) return { text: spec.format((this.scope.getSnapshot().value as any)?.[field]), overridden: !!(this.scope.getSnapshot().user && Object.hasOwn(this.scope.getSnapshot().user as any, field)), invalid: false }; const write = staged.clear ? { kind: 'clear' as const } : spec.parse(staged.text); return { text: staged.text, overridden: write?.kind === 'set', invalid: write === undefined } }
  actions(): CardActions { return { edit: (f, t) => { this.staged.set(f, { text: t, clear: false }); this.failed = false; this.publish() }, resetField: (f) => { const spec = this.specs.get(f)!; const base = (this.scope.getSnapshot().base as any)?.[f]; this.staged.set(f, { text: spec.format(base), clear: true }); this.failed = false; this.publish() }, save: () => { void this.save() }, discard: () => { this.staged.clear(); this.failed = false; this.publish() } } }
  private async save(): Promise<void> { const plan = this.plan(); const writes = plan.flatMap(p => p.run ? [p.run] : []); if (plan.length === 0 || this.saving || writes.length !== plan.length) return; this.saving = true; this.failed = false; this.publish(); let ok = true; for (const w of writes) ok = (await w()) && ok; if (ok) this.staged.clear(); this.saving = false; this.failed = !ok; this.publish() }
  private plan(): PlannedWrite[] { const plan: PlannedWrite[] = []; const snap = this.scope.getSnapshot(); const val = snap.value as any; const user = snap.user as any; for (const [field, staged] of this.staged) { const spec = this.specs.get(field)!; if (staged.clear) { if (user && Object.hasOwn(user, field)) plan.push({ field, run: async () => { await this.scope.unset(field); return !(this.scope.getSnapshot().user as any)?.[field] } }); continue } if (staged.text === spec.format(val?.[field])) continue; const write = spec.parse(staged.text); if (!write) plan.push({ field, run: undefined }); else if (write.kind === 'clear') plan.push({ field, run: async () => { await this.scope.unset(field); return !(this.scope.getSnapshot().user as any)?.[field] } }); else plan.push({ field, run: async () => { await this.scope.set(field, write.value); return (this.scope.getSnapshot().user as any)?.[field] === write.value } }) } return plan }
  private publish() { for (const l of this.listeners) l() }
}
